### ISSUE TITLE
Issues when adding multiple agents

### ISSUE THREAD

**Issue by Pyrofoux** [mgarciaortiz/simple-playgrounds#25]
Hi! I encountered two blocking issues when working with multiple agents in my playground. 

First one: 

````
  File "C:\Users\Younès\Desktop\FLOWERS\vivarium\vivarium\RPS_demo.py", line 110, in run
    game = Engine(playground=pg, agents=agents, time_limit = steps, screen=display)
  File "D:\Anaconda\lib\site-packages\simple_playgrounds\game_engine.py", line 57, in __init__
    raise ValueError('Could not place agent without overlapping')
ValueError: Could not place agent without overlapping
````

I understand that handling overlapping agents at startup is a new (useful!) feature. But in my case its a bit hindering me, as I need handle like 100s of agents and I don't mind if they overlap at first. In the previous versions, the collisions system of Pymunk used to do the job and push everything without overlaping in the first two steps. I'd like to use this way rather than having the probability that my experiment won't start because of overlapping agents.

Here's what I suggest: just like entities, add a `allow_overlapping` property to agents, and add them directly if set to `True`.

Second one:

When I create a new agent directly with `pg.add_agent`, it isn't added in `game.agents`. Here `game` is this object.
```
game = Engine(playground=pg, agents=agents, time_limit = steps, screen=display)
```

This means that I can't use the traditional loop to apply actions to agents, here below:
```
for agent in game.agents:
            next_actions = agent.behavior.get_next_actions()
            actions[agent.name] = next_actions

game.step(actions)
```

In fact, this code will raise this error: 
```
  File "C:\Users\Younès\Desktop\FLOWERS\vivarium\vivarium\RPS_demo.py", line 131, in run
    game.step(actions)
  File "D:\Anaconda\lib\site-packages\simple_playgrounds\game_engine.py", line 141, in step
    agent.apply_actions_to_body_parts(actions[agent.name])
KeyError: 'agent_30'
````

Effectively, these two issues mean there is no easy way to add a number of agents with an order of magnitude where overlapping is common. (n >= 30)

Let's work something out ! 😄

**Comment by mgarciaortiz** [comment]
Hi,

So I did two things:
- now you an only add agents through playgronds. You don't pass them as arguments in game engine.
- agents accept an additional keyword argument: allow_overlapping. It is True y default. If set to false, it will raise an error in the case where the playground can't place the agent.

Can you test if it works for you?

**Comment by Pyrofoux** [comment]
Yes, these issues are no more there when adding agents. Thanks a lot ! 😄
